### ISSUE TITLE
Simulation run time exceeding an hour

### ISSUE THREAD

**Issue by vjkrishna023** [softmaterialslab/np-assembly-lab#12]
The Nano Particle Assembly tool simulation ran for more than an hour without any update in the progress bar, and eventually I had to cancel the simulation. This issue seems to occur approximately one in twenty times I try to run a simulation.
![1 np_assembly](https://user-images.githubusercontent.com/43117289/53692446-16306000-3d5e-11e9-8092-56c4010e7846.JPG)

**Comment by kadupitiya** [comment]
@vjkrishna023: Is this still an issue?

**Comment by vijayakrishna23** [comment]
The simulation run time didn't exceed an hour always in the past, only at few instances. Recently, I didn't face this issue. So I will close this one.
