### ISSUE TITLE
Atoms appears outside the cube

### ISSUE THREAD

**Issue by vijayakrishna23** [softmaterialslab/np-assembly-lab#14]
While the simulation is running the atoms (red) appears to be outside the cube at some instances in the simulation snapshot page. 
![Screenshot (54)](https://user-images.githubusercontent.com/47954682/57573355-0dd26080-7444-11e9-89ac-316dd4d786a3.png)

**Comment by nbrunk** [comment]
This is probably OK. If atom centers are near the periodic boundary it puts
them there and renders it with then sticking out slightly. As long as they
aren't way outside, it's alright.

Nick

**Comment by vijayakrishna23** [comment]
Got it. They aren't way outside. I will close this issue for now. Thanks!

Vijay
